name: Build rkp-ipid for GL-MT6000
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 安装完整编译依赖
        run: |
          sudo apt update
          sudo apt install -y build-essential git flex bison gawk gettext \
            libssl-dev libncurses5-dev libncursesw5-dev \
            zlib1g-dev libelf-dev libffi-dev openssl libdeflate-dev  # 新增缺失依赖

      - name: 克隆 OpenWrt 源码
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          path: openwrt
          ref: v23.05.0  # 建议使用稳定版本分支，降低兼容性问题

      - name: 添加 rkp-ipid 软件包
        run: |
          cd openwrt/package
          git clone https://github.com/CHN-beta/rkp-ipid.git rkp-ipid

      - name: 配置编译选项
        run: |
          cd openwrt
          echo "CONFIG_TARGET_mediatek=y" >> .config
          echo "CONFIG_TARGET_mediatek_filogic=y" >> .config
          echo "CONFIG_TARGET_mediatek_filogic_GL-MT6000=y" >> .config
          echo "CONFIG_PACKAGE_kmod-rkp-ipid=y" >> .config
          make defconfig

      - name: 编译 rkp-ipid 模块
        run: |
          cd openwrt
          make package/rkp-ipid/compile -j$(nproc) V=s

      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: kmod-rkp-ipid-gl-mt6000
          path: openwrt/bin/packages/aarch64_cortex-a53/base/kmod-rkp-ipid_*.ipk
