name: Build rkp-ipid for GL-MT6000
on:
  workflow_dispatch:  # 手动触发编译

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 安装编译依赖
        run: |
          sudo apt update
          sudo apt install -y build-essential git flex bison gawk gettext

      - name: 克隆 OpenWrt 源码
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          path: openwrt
          ref: main  # 可指定稳定版本分支，如 v23.05

      - name: 添加 rkp-ipid 软件包
        run: |
          cd openwrt/package
          git clone https://github.com/CHN-beta/rkp-ipid.git rkp-ipid

      - name: 配置编译选项
        run: |
          cd openwrt
          # 配置 GL-MT6000 目标（MediaTek Filogic 830, aarch64_cortex-a53）
          echo "CONFIG_TARGET_mediatek=y" >> .config
          echo "CONFIG_TARGET_mediatek_filogic=y" >> .config
          echo "CONFIG_TARGET_mediatek_filogic_GL-MT6000=y" >> .config
          echo "CONFIG_PACKAGE_kmod-rkp-ipid=y" >> .config
          make defconfig  # 生成默认配置

      - name: 编译 rkp-ipid 模块
        run: |
          cd openwrt
          make package/rkp-ipid/compile -j$(nproc) V=s  # 详细输出编译过程

      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: kmod-rkp-ipid-gl-mt6000
          path: openwrt/bin/packages/aarch64_cortex-a53/base/kmod-rkp-ipid_*.ipk
